### ISSUE TITLE
Cannot find a library instance of "AceComm-3.0"

### ISSUE THREAD

**Issue by vrnvorona** [kaminaris/AuctionFaster#59]
Message: Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceComm-3.0".
Time: Fri Aug 30 16:18:09 2019
Count: 1
Stack: Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceComm-3.0".
[C]: ?
...Ons\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:189: in function `EmbedLibrary'
...Ons\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:171: in function `EmbedLibraries'
...ddOns\DBM-Core\Libs\ThreatClassic-1.0\ThreatBoot.lua:20: in main chunk

Locals: (*temporary) = "Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceComm-3.0"."

**Comment by pwilkowski** [comment]
This looks like issue of other addons. AuctionFaster doesn't use AceComm-3.0. there is not a single occurance of "AceComm" in it's code.

It may look like issue from auctionfaster because Ace libs are loaded once. This one may come from DBM:
`...ddOns\DBM-Core\Libs\ThreatClassic-1.0\ThreatBoot.lua:20: in main chunk`
