### ISSUE TITLE
[Feature Request] Scan All AH prices

### ISSUE THREAD

**Issue by Mysame** [kaminaris/AuctionFaster#91]
I love how neatly this addon displays AH prices in tooltips. But it only shows for items I've specifically looked up. It would be nice to scan the entire AH and get all prices.

**Comment by pwilkowski** [comment]
This feature will never be implemented because of 2 reasons:
1. Big amount of data significantly delays load screens
2. If you need tooltips, much better option is to have TSM + their app alongside with auctionfaster

Also this addon is meant for quick dumping/buying stuff on AH, not create some elaborate pricing strategies based on historical data.
